# Form implementation generated from reading ui file 'gui\gui_interface.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(558, 695)
        font = QtGui.QFont()
        font.setFamily("Monocraft")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        Main.setFont(font)
        Main.setStyleSheet("/* ================================================\n"
"   MODERN FLAT & FRAMED - LIGHT THEME SYSTEM v1\n"
"   Font: JetBrainsMonoNL Nerd Font Mono\n"
"   Style: Rounded/Card | Accent: #1c68b5\n"
"   ================================================ */\n"
"\n"
"/* --- MAIN WINDOW & GLOBAL TEXT --- */\n"
"QMainWindow, QWidget {\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"    font-family: \"Monocraft\";\n"
"    font-size: 7.9pt;\n"
"    selection-background-color: #1c68b5;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"/* --- CONTAINERS (Restored \"Cut\" Border) --- */\n"
"QGroupBox {\n"
"    border: 1px solid #bfbfbf;\n"
"    border-radius: 4px;\n"
"    margin-top: 8px;\n"
"    /* Reduced from 20px to 8px to align title with border */\n"
"    padding-top: 8px;\n"
"}\n"
"QGroupBox::title {\n"
"    color: #000000;\n"
"    subcontrol-origin: margin; /* Text sits in the margin */\n"
"    left: 10px;\n"
"    padding: 0 3px; /* Small padding covers the border behind the text */\n"
"}\n"
"\n"
"/* --- PROGRESS BAR (Rounded) --- */\n"
"QProgressBar {\n"
"    border: 1px solid #bfbfbf;\n"
"    border-radius: 4px; /* Rounds the container */\n"
"    text-align: center;\n"
"    background-color: #f5f5f5;\n"
"    color: #000000;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #1c68b5;\n"
"    border-radius: 4px; /* Rounds the internal bar */\n"
"}\n"
"\n"
"/* --- BUTTONS --- */\n"
"QPushButton {\n"
"    /* DEFAULT STATE (LIGHT GRAY) */\n"
"    background-color: #e1e1e1;\n"
"    color: #000000;\n"
"\n"
"    /* Geometry */\n"
"    border-radius: 4px;\n"
"    padding: 6px 16px;\n"
"\n"
"    /* IMPORTANT: Create a 2px invisible border.\n"
"       We color this border match the background so the button stays the \n"
"       same size when the border turns dark on hover.\n"
"    */\n"
"    border: 1px solid #e1e1e1; \n"
"}\n"
"\n"
"/* GLOBAL HOVER (Applies to the default Light Gray button) */\n"
"QPushButton:hover {\n"
"    background-color: #eeeeee;\n"
"    /* Lighten the Gray */\n"
"    border-color: #333333;\n"
"    /* The \"Pop\" (Dark Ring for contrast against light bg) */\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #cccccc;\n"
"    border-color: #cccccc;\n"
"}\n"
"\n"
"/* --- INPUT FIELDS --- */\n"
"QLineEdit, QTextEdit, QPlainTextEdit, QSpinBox, QDoubleSpinBox, QComboBox {\n"
"    background-color: #f5f5f5; /* Slightly darker than main window */\n"
"    border: 1px solid #bfbfbf;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    color: #000000;\n"
"}\n"
"QLineEdit:focus, QTextEdit:focus, QSpinBox:focus, QComboBox:focus {\n"
"    border: 1px solid #1c68b5;\n"
"}\n"
"\n"
"/* --- DATA VIEWS (Card Look) --- */\n"
"QTableWidget, QListWidget, QTreeWidget {\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #bfbfbf;\n"
"    border-radius: 4px;\n"
"    gridline-color: transparent;\n"
"    outline: none;\n"
"}\n"
"QTableWidget::item, QListWidget::item, QTreeWidget::item {\n"
"    padding: 5px;\n"
"    border-bottom: 1px solid #e0e0e0;\n"
"    color: #000000;\n"
"}\n"
"QTableWidget::item:selected, QListWidget::item:selected, QTreeWidget::item:selected {\n"
"    background-color: #1c68b5;\n"
"    color: #ffffff;\n"
"    border-bottom: 1px solid #1c68b5;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #e1e1e1;\n"
"    color: #000000;\n"
"    padding: 5px;\n"
"    border: none;\n"
"    border-bottom: 1px solid #bfbfbf;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* --- SCROLLBARS (Thin) --- */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #ffffff;\n"
"    width: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #c1c1c1;\n"
"    min-height: 20px;\n"
"    border-radius: 5px;\n"
"    margin: 2px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #a8a8a8;\n"
"}\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #ffffff;\n"
"    height: 10px;\n"
"    margin: 0px 0px 0px 0px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #c1c1c1;\n"
"    min-width: 20px;\n"
"    border-radius: 5px;\n"
"    margin: 2px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #a8a8a8;\n"
"}\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"\n"
"/* =========================================================================\n"
"   CHECKBOXES & RADIOS\n"
"   Unchecked Hover = Dark Grey (#666666)\n"
"   Checked Hover   = Bright Blue (#4fa4ff equivalent)\n"
"   ========================================================================= */\n"
"\n"
"QCheckBox, QRadioButton {\n"
"    spacing: 8px;\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* --- CHECKBOX INDICATOR --- */\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #bfbfbf;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Hover on UNCHECKED box (Darker Grey) */\n"
"QCheckBox::indicator:hover {\n"
"    background-color: #e0e0e0;\n"
"    border-color: #666666;\n"
"}\n"
"\n"
"/* Checked State (Blue) */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #1c68b5;\n"
"    border-color: #1c68b5;\n"
"}\n"
"\n"
"/* Hover on CHECKED box (Brighter Blue) */\n"
"QCheckBox::indicator:checked:hover {\n"
"    background-color: #3a8ee6;\n"
"    border-color: #3a8ee6;\n"
"}\n"
"\n"
"\n"
"/* --- RADIO INDICATOR --- */\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #bfbfbf;\n"
"    border-radius: 8px; /* Circle */\n"
"}\n"
"\n"
"/* Hover on UNCHECKED circle (Darker Grey) */\n"
"QRadioButton::indicator:hover {\n"
"    background-color: #e0e0e0;\n"
"    border-color: #666666;\n"
"}\n"
"\n"
"/* Checked State (Blue) */\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #1c68b5;\n"
"    border-color: #1c68b5;\n"
"}\n"
"\n"
"/* Hover on CHECKED circle (Brighter Blue) */\n"
"QRadioButton::indicator:checked:hover {\n"
"    background-color: #3a8ee6;\n"
"    border-color: #f5f5f5; \n"
"    /* Keep the inner ring light! */\n"
"}\n"
"\n"
"/* --- TAB WIDGET --- */\n"
"QTabWidget::pane {\n"
"    border: 1px solid #bfbfbf;\n"
"    border-radius: 4px;\n"
"    background-color: #ffffff;\n"
"    top: -1px;\n"
"}\n"
"QTabBar::tab {\n"
"    background: #e1e1e1;\n"
"    color: #666666;\n"
"    border: 1px solid transparent;\n"
"    padding: 8px 16px;\n"
"    margin-right: 2px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background: #ffffff;\n"
"    color: #1c68b5;\n"
"    border-bottom: 2px solid #1c68b5;\n"
"}\n"
"QTabBar::tab:hover {\n"
"    background: #f0f0f0;\n"
"    color: #000000;\n"
"}\n"
"\n"
"/* --- MENUS --- */\n"
"QMenuBar {\n"
"    background-color: #ffffff;\n"
"    border-bottom: 1px solid #bfbfbf;\n"
"}\n"
"QMenuBar::item {\n"
"    background-color: transparent;\n"
"    padding: 8px 12px;\n"
"    color: #000000;\n"
"}\n"
"QMenuBar::item:selected {\n"
"    background-color: #e1e1e1;\n"
"}\n"
"QMenu {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #bfbfbf;\n"
"    padding: 5px;\n"
"    color: #000000;\n"
"}\n"
"QMenu::item {\n"
"    padding: 5px 20px;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color: #1c68b5;\n"
"    color: #ffffff;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"/* --- TOOLTIPS --- */\n"
"QToolTip {\n"
"    background-color: #f5f5f5;\n"
"    color: #000000;\n"
"    border: 1px solid #bfbfbf;\n"
"    padding: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* --- SLIDERS --- */\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #bfbfbf;\n"
"    height: 4px;\n"
"    background: #f5f5f5;\n"
"    margin: 2px 0;\n"
"    border-radius: 2px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: #1c68b5;\n"
"    border: 1px solid #1c68b5;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    margin: -6px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"/* =========================================================================\n"
"   CONTENT BOX (Using QScrollArea)\n"
"   ========================================================================= */\n"
"\n"
"QScrollArea {\n"
"    background-color: #f5f5f5;      /* Inset Background */\n"
"    border: 1px solid #bfbfbf;      /* Standard Border */\n"
"    border-radius: 4px;             /* Rounded Corners */\n"
"}\n"
"\n"
"/* This targets the \"viewport\" (the internal canvas that holds the widget) */\n"
"QScrollArea > QWidget > QWidget {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"\n"
"/* Optional: Clean up standard borders if they conflict */\n"
"QScrollArea > QWidget > QWidget {\n"
"    border: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=Main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 200))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setBaseSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/dark/home_directory.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.radioButton = QtWidgets.QRadioButton(parent=self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/dark/ads_close_hover.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.radioButton.setIcon(icon1)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/dark/dialog_save.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.checkBox_2.setIcon(icon2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.groupBox_2)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_3.addWidget(self.plainTextEdit)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalSlider = QtWidgets.QSlider(parent=self.groupBox_3)
        self.verticalSlider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.gridLayout_2.addWidget(self.verticalSlider, 1, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(parent=self.groupBox_3)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 0, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(parent=self.groupBox_3)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_2.addWidget(self.horizontalSlider, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 31))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(parent=self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(parent=self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSwitch_Theme = QtWidgets.QMenu(parent=self.menuView)
        self.menuSwitch_Theme.setObjectName("menuSwitch_Theme")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(parent=Main)
        self.actionExit.setObjectName("actionExit")
        self.actionUsage = QtGui.QAction(parent=Main)
        self.actionUsage.setObjectName("actionUsage")
        self.actionDark = QtGui.QAction(parent=Main)
        self.actionDark.setObjectName("actionDark")
        self.actionLight = QtGui.QAction(parent=Main)
        self.actionLight.setObjectName("actionLight")
        self.actionAbout = QtGui.QAction(parent=Main)
        self.actionAbout.setObjectName("actionAbout")
        self.actionToggle_Theme_Ctrl_T = QtGui.QAction(parent=Main)
        self.actionToggle_Theme_Ctrl_T.setObjectName("actionToggle_Theme_Ctrl_T")
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionUsage)
        self.menuHelp.addAction(self.actionAbout)
        self.menuSwitch_Theme.addAction(self.actionDark)
        self.menuSwitch_Theme.addAction(self.actionLight)
        self.menuView.addAction(self.menuSwitch_Theme.menuAction())
        self.menuView.addAction(self.actionToggle_Theme_Ctrl_T)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "PyQt6 Template"))
        self.label.setText(_translate("Main", "Switch Theme will switch the icons color."))
        self.groupBox.setTitle(_translate("Main", "Buttons"))
        self.pushButton.setText(_translate("Main", "Push Button"))
        self.pushButton.setProperty("icon_name", _translate("Main", "home_directory"))
        self.radioButton.setText(_translate("Main", "Radio Button"))
        self.radioButton.setProperty("icon_name", _translate("Main", "ads_close_hover"))
        self.checkBox.setText(_translate("Main", "Check box"))
        self.checkBox_2.setText(_translate("Main", "Check box with an image"))
        self.checkBox_2.setProperty("icon_name", _translate("Main", "dialog_save"))
        self.groupBox_2.setTitle(_translate("Main", "Text edit"))
        self.label_2.setText(_translate("Main", "Line edit :"))
        self.label_3.setText(_translate("Main", "Plain text edit :"))
        self.groupBox_3.setTitle(_translate("Main", "Sliders / Bars"))
        self.menuFIle.setTitle(_translate("Main", "File"))
        self.menuHelp.setTitle(_translate("Main", "Help"))
        self.menuView.setTitle(_translate("Main", "View"))
        self.menuSwitch_Theme.setTitle(_translate("Main", "Theme"))
        self.actionExit.setText(_translate("Main", "Exit"))
        self.actionUsage.setText(_translate("Main", "Usage"))
        self.actionDark.setText(_translate("Main", "Dark"))
        self.actionLight.setText(_translate("Main", "Light"))
        self.actionAbout.setText(_translate("Main", "About"))
        self.actionToggle_Theme_Ctrl_T.setText(_translate("Main", "Toggle Theme"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec())
